### ISSUE TITLE
When to release the dataset

### ISSUE THREAD

**Issue by whuhxb** [Nathan-UW/OpenGF#1]
Hi Authors:

    Good to see this nice work! Looking forward to the release of the dataset and code. Thanks a lot.
    Best wishes.

Xiaobing

**Comment by Nathan-UW** [comment]
Hey @whuhxb ,
     (1) The dataset has been released, please refer to the Google Drive or BaiduYun link listed in this resource.
     (2) All baselines of the OpenGF dataset come from Open source code or Free software, please refer to the links marked in the paper.

Best wishes
