### ISSUE TITLE
About source code（关于源码）

### ISSUE THREAD

**Issue by Kelvin-wen** [Nathan-UW/OpenGF#3]
作者您好，感谢您在点云地面滤波领域做出的贡献。我目前也正在研究点云地面滤波的深度学习算法。我想要在下一个研究中使用您的OpenGF数据集，但是由于OpenGF与S3DIS、ShapeNet等数据集差异较大，导致我在使用这些源码进行训练和测试时遇到了困难。我看到您在论文《Deep learning for filtering the ground from ALS point clouds: A dataset,evaluations and issues》中，很好的重现了在OpenGF数据集上的多个网络的训练和测试。因此，想请问您，可以将您重现的这些网络的源码分享一下吗？
再次感谢。

Hello, thank you for your contribution in the field of point cloud ground filtering. I am currently researching deep learning algorithms for point cloud ground filtering as well. I would like to use your OpenGF dataset in my next research project. However, I have encountered difficulties when using the existing source code for training and testing, as there are significant differences between the OpenGF dataset and other datasets such as S3DIS and ShapeNet.

I noticed in your paper "Deep learning for filtering the ground from ALS point clouds: A dataset, evaluations and issues" that you have successfully reproduced the training and testing of multiple networks on the OpenGF dataset. Therefore, I would like to ask if it is possible for you to share the source code for these reproduced networks.

Thank you once again for your contribution.

Sincerely,

**Comment by Nathan-UW** [comment]
@Kelvin-wen 
https://github.com/WeikaiTan/RandLA-Net. Hope it will be useful to you.

**Comment by 2578562306** [comment]
> 作者您好，感谢您在点云地面反馈领域做出的贡献。我目前也在研究点云地面反馈的深度学习算法。我想在下一个研究中使用您的OpenGF数据集，但是由于OpenGF与S3DIS、ShapeNet等数据集差异加大，导致我在使用这些源码进行训练和测试时遇到困难。我在论文《Deep Learning for Filtering the Ground from ALS pointcloud: A dataset,evaluations and issues》中，很好的重置了在OpenGF数据集上的多个网络的训练和测试。，想请问您，可以将您重置的这些网络的源码分享一下吗？ 再次感谢。
> 
> 您好，感谢您在点云地面滤波领域的贡献。我目前也在研究点云地面滤波的深度学习算法。我希望在下一个研究项目中使用您的 OpenGF 数据集。但是，在使用现有源代码进行训练和测试时，我遇到了困难，因为 OpenGF 数据集与 S3DIS 和 ShapeNet 等其他数据集之间存在显著差异。
> 
> 我注意到，在您的论文《深度学习从 ALS 点云中过滤地面：数据集、评估和问题》中，您已成功复现了 OpenGF 数据集上多个网络的训练和测试。因此，我想问您是否可以分享这些复现网络的源代码。
> 
> 再次感谢您的贡献。
> 
> 真挚地，

哥们实验做出来了吗？？方便的话可以共享下吗

**Comment by HairyCrabo** [comment]
同问，同时感谢作者在点云地面滤波领域做出的贡献。
