### ISSUE TITLE
OpenGF Non-standard Point Format 

### ISSUE THREAD

**Issue by GabrielePaolini** [Nathan-UW/OpenGF#4]
Hello, thank you for your work on this dataset.
I plan to use your dataset to conduct a series of experiments on ground filtering.
To preprocess las/laz files I use Cloudcompare and then laspy to read them on Python.
It seems that your laz files have an unconventional point format (e.g. 129 or 134) which both Cloudcompare and laspy cannot understand. 
As a matter of fact, when I re-save these files, I often get distorted xyz coordinates or more simply an error (invalid dataformat_id).

How do you manage to read and process these files? 

Thank you again for your contribution.

**Comment by Nathan-UW** [comment]
Hi, thanks for your interest,
I just tried to randomly download a LAZ file from Google Drive, and then successfully open it with the latest version of CloudCompare and output it as a PLY file. I haven't encountered the problem you mentioned before. Please download the latest version of cloudcompare and try again.

**Comment by Nathan-UW** [comment]
Hi, @GabrielePaolini 
Thanks for your interest.
I just tried to randomly download a LAZ file from Google Drive, and then successfully open it with the latest version of CloudCompare and output it as a PLY file. I haven't encountered the problem you mentioned before. Please download the latest version of CloudCompare and try again.

**Comment by GabrielePaolini** [comment]
Hi @Nathan-UW, thank you for your help.
I can confirm that the problem was present in an older version of CloudCompare (2.11) which was the one installed on my computer. 
By installing the latest version of CC (2.13) I can read the dataset in the correct point format and save it as a LAS file without problems.
Thank you very much!
